workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build unsigned IPA
        script: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/Runner.app
          zip -r life_good.ipa Payload
    artifacts:
      - build/ios/iphoneos/life_good.ipa