name: iOS Build and Release

on:
  push:
    tags:
      - 'v*' # Срабатывает только тогда, когда вы пушите тег версии (например, v1.0.1)

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.x' # Укажите вашу версию Flutter, если необходимо
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    # Собираем iOS проект без подписи (для AltStore)
    - name: Build iOS
      run: flutter build ios --release --no-codesign

    # Создаем правильную структуру папок и архивируем в .ipa
    - name: Package IPA
      run: |
        cd build/ios/iphoneos
        mkdir Payload
        cd Payload
        ln -s ../Runner.app
        cd ..
        zip -r app.ipa Payload

    # Создаем релиз на GitHub и прикрепляем туда готовый app.ipa
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/ios/iphoneos/app.ipa
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
